#!/bin/bash

# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -e

# https://github.com/sclorg/postgresql-container/blob/e111ece2074e80b8da33b8d58e48e6d4c383d2db/9.5/root/usr/bin/cgroup-limits
# : is shell builtin command. please check bash(1) man page for more info
: '
Variables currently supported:

  MEMORY_LIMIT_IN_BYTES
    Maximum amount of user memory in bytes.

  MEMORY_LIMIT_IN_MEGABYTES
    Converting MEMORY_LIMIT_IN_BYTES

  NUMBER_OF_CORES
    Number of detected CPU cores that can be used.

  PHYSICAL_MEM
    Amount of host physical memory in bytes.

  NO_MEMORY_LIMIT
    Set to "true" if MEMORY_LIMIT_IN_BYTES is equal or higher 
    than PHYSICAL_MEM. Undefined otherwise.
'
function read_file() {
  local FILE="${1}"
  local FILE_CONTENT=""
  FILE_CONTENT=$(cat "${FILE}" 2>/dev/null)
  echo "${FILE_CONTENT}"
}

MEMORY_LIMIT_IN_BYTES=""
MEMORY_LIMIT_IN_BYTES="$(cgget -n --values-only --variable memory.limit_in_bytes /)"
MEMORY_LIMIT_IN_MEGABYTES=$(awk -v MEM="${MEMORY_LIMIT_IN_BYTES}" 'BEGIN { print MEM/1048576 }')

NUMBER_OF_CORES=""
NUMBER_OF_CORES=$(cgget -n --values-only --variable cpuset.cpus /)
ARRAY=( ${NUMBER_OF_CORES//-/ } )
if [[ "${#ARRAY[@]}" -eq 2 ]]; then
  NUMBER_OF_CORES=$(awk -v POS1="${ARRAY[0]}" -v POS2="${ARRAY[1]}" 'BEGIN { print POS2-POS1+1 }')
else
  NUMBER_OF_CORES=$((NUMBER_OF_CORES+1))
fi

PHYSICAL_MEM=""
PHYSICAL_MEM=$(free -b | awk 'NR==2{print$2}')

NO_MEMORY_LIMIT=""
if [[ "${MEMORY_LIMIT_IN_BYTES}" -ge "${PHYSICAL_MEM}" ]]; then
  NO_MEMORY_LIMIT="true"
fi
